{
"name": "TPJ Tax Updates Check",
"on": {
"workflow_dispatch": {},
"schedule": [
{
"cron": "30 3 * * *"
}
]
},
"jobs": {
"check-updates": {
"runs-on": "ubuntu-latest",
"steps": [
  {
"name": "Check time",
"shell": "bash",
"run": "echo \"TPJ Tax & Insurance Deadlines Monitor\"\necho \"Automatic daily check started.\"\ndate"
}
]
}
}
}
